// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web.Data;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(iFindContext))]
    [Migration("20251118135115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web.Models.Dogodek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumCas")
                        .HasColumnType("datetime2");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("OrganizatorId");

                    b.ToTable("Dogodki", (string)null);
                });

            modelBuilder.Entity("web.Models.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorije", (string)null);
                });

            modelBuilder.Entity("web.Models.Lokacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DogodekId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DogodekId")
                        .IsUnique();

                    b.ToTable("Lokacije", (string)null);
                });

            modelBuilder.Entity("web.Models.Udelezba", b =>
                {
                    b.Property<int>("UporabnikId")
                        .HasColumnType("int");

                    b.Property<int>("DogodekId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.HasKey("UporabnikId", "DogodekId");

                    b.HasIndex("DogodekId");

                    b.ToTable("Udelezbe", (string)null);
                });

            modelBuilder.Entity("web.Models.Uporabnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Geslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JeAdministrator")
                        .HasColumnType("bit");

                    b.Property<bool>("JeOrganizator")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priimek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Spol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Uporabniki", (string)null);
                });

            modelBuilder.Entity("web.Models.Dogodek", b =>
                {
                    b.HasOne("web.Models.Kategorija", "Kategorija")
                        .WithMany("Dogodki")
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web.Models.Uporabnik", "Organizator")
                        .WithMany("OrganiziraniDogodki")
                        .HasForeignKey("OrganizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Organizator");
                });

            modelBuilder.Entity("web.Models.Lokacija", b =>
                {
                    b.HasOne("web.Models.Dogodek", "Dogodek")
                        .WithOne("Lokacija")
                        .HasForeignKey("web.Models.Lokacija", "DogodekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dogodek");
                });

            modelBuilder.Entity("web.Models.Udelezba", b =>
                {
                    b.HasOne("web.Models.Dogodek", "Dogodek")
                        .WithMany("Udelezbe")
                        .HasForeignKey("DogodekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web.Models.Uporabnik", "Uporabnik")
                        .WithMany("Udelezbe")
                        .HasForeignKey("UporabnikId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Dogodek");

                    b.Navigation("Uporabnik");
                });

            modelBuilder.Entity("web.Models.Dogodek", b =>
                {
                    b.Navigation("Lokacija");

                    b.Navigation("Udelezbe");
                });

            modelBuilder.Entity("web.Models.Kategorija", b =>
                {
                    b.Navigation("Dogodki");
                });

            modelBuilder.Entity("web.Models.Uporabnik", b =>
                {
                    b.Navigation("OrganiziraniDogodki");

                    b.Navigation("Udelezbe");
                });
#pragma warning restore 612, 618
        }
    }
}
